server:
  http:
    address: localhost:8080
  grpc:
    address: localhost:9080
authn:
  psk:
    pre-shared-key-file: config/psks.yaml 
authz:
  impl: allow-all
eventing:
  eventer: stdout
  kafka:
storage:
  database: sqlite3
  sqlite3:
    dsn: inventory.db
  postgres:
    host: "localhost"
    port: "5432"
    user:
    password:
    dbname:
