services:
  inventory-api:
    environment:
      - "INVENTORY_API_CONFIG=/inventory-api-compose.yaml"
#      - "INVENTORY_API_STORAGE_DBNAME=postgres"
#      - "INVENTORY_API_STORAGE_POSTGRES_DBNAME=database"
#      - "INVENTORY_API_STORAGE_POSTGRES_USER=${POSTGRES_USER}"
#      - "INVENTORY_API_STORAGE_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    build:
      dockerfile: Dockerfile
    configs:
      - source: inventory_file
        target: /inventory-api-compose.yaml
    command: ["serve"]
    restart: "always"
    ports:
      - "8081:8081"
      - "9081:9081"
    depends_on:
      invmigrate:
        condition: service_completed_successfully

  invmigrate:
    environment:
      - "INVENTORY_API_CONFIG=/inventory-api-compose.yaml"
    build:
      dockerfile: Dockerfile
    configs:
      - source: inventory_file
        target: /inventory-api-compose.yaml
    command: ["migrate"]
    restart: "never"
    depends_on:
      invdatabase:
        condition: service_started

  invdatabase:
    image: "postgres"
    command: ["-p", "5433","-c", "track_commit_timestamp=on"]
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DBNAME}"
      - "PGPORT=5433"

  relations-api:
    image: "quay.io/cloudservices/kessel-relations:latest"
    environment:
      - "SPICEDB_PRESHARED=${SPICEDB_GRPC_PRESHARED_KEY}"
      # - "SPICEDB_PRESHARED_FILE=/run/secrets/spicedb_pre_shared"
      - "SPICEDB_ENDPOINT=spicedb:50051"
    profiles: ["relations-api"]
    secrets:
      - spicedb_pre_shared
    restart: "always"
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      spicedb:
        condition: service_started

  spicedb:
    image: "authzed/spicedb"
    command: "serve"
    restart: "always"
    configs:
      - bootstrap_file
    secrets:
      - spicedb_pre_shared
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50051:50051"
    environment:
      - "SPICEDB_GRPC_PRESHARED_KEY=${SPICEDB_GRPC_PRESHARED_KEY}"
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_BOOTSTRAP_FILES=/bootstrap_file"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/spicedb?sslmode=disable"
    depends_on:
      migrate:
        condition: service_completed_successfully

  migrate:
    image: "authzed/spicedb"
    command: "datastore migrate head"
    restart: "never"
    secrets:
      - spicedb_pre_shared
    environment:
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/spicedb?sslmode=disable"
    depends_on:
      database:
        condition: service_started

  database:
    image: "postgres"
    command: -c track_commit_timestamp=on
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DBNAME}"

configs:
  spicedb_pre_shared:
    environment: "SPICEDB_GRPC_PRESHARED_KEY"
  bootstrap_file:
    file: ./deploy/schema.yaml
  inventory_file:
    file: ./inventory-api-compose.yaml

secrets:
  spicedb_pre_shared:
    file: ./.secrets/local-spicedb-secret
