name: CI v1beta2 Test and Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-test-and-coverage-v1beta2:
    name: Build, Test, and Coverage v1beta2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Install Go dependencies
        run: go get ./...
        shell: bash

      - name: Run v1beta2 Unit Tests (precise coverage)
        run: |
          echo "Running v1beta2 unit tests..."
          COVERPKG=$(go list -deps ./api/kessel/inventory/v1beta2/... ./internal/service/resources | grep 'github.com/project-kessel/inventory-api' | paste -sd "," -)
          echo "COVERPKG: $COVERPKG"
          go test -short -covermode=atomic \
            -coverpkg=$COVERPKG \
            -coverprofile=v1beta2-coverage.out \
            ./api/kessel/inventory/v1beta2/... ./internal/service/resources
        shell: bash

      - name: Summarize v1beta2 Coverage
        run: |
          cd $GITHUB_WORKSPACE
          echo "### Merging this branch will **increase** overall coverage" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "<details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<summary>Coverage by file</summary>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          go tool cover -func=v1beta2-coverage.out >> "$GITHUB_STEP_SUMMARY"
          echo "</details>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "### Total Coverage:" >> "$GITHUB_STEP_SUMMARY"
          go tool cover -func=v1beta2-coverage.out | grep total | awk '{print "**"$3"**"}' | tee -a "$GITHUB_STEP_SUMMARY"
        shell: bash
