name: v1beta2 unit test coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  v1beta2-unit-test-coverage:
    name: v1beta2 unit test coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Install Go dependencies
        run: go get ./...
        shell: bash

      - name: Run v1beta2 Unit Tests (precise coverage)
        run: |
          echo "Running v1beta2 unit tests..."
          COVERPKG=$(go list -deps ./api/kessel/inventory/v1beta2/... ./internal/service/resources | grep 'github.com/project-kessel/inventory-api' | grep -v '/v1beta1/' | paste -sd "," -)
          echo "COVERPKG: $COVERPKG"
          go test -short -covermode=atomic \
            -coverpkg=$COVERPKG \
            -coverprofile=v1beta2-coverage.out \
            ./api/kessel/inventory/v1beta2/... ./internal/service/resources
        shell: bash

      - name: Summarize v1beta2 Coverage
        run: |
          echo "<details>" >> "$GITHUB_STEP_SUMMARY"
          echo "<summary>Coverage by function (top level)</summary>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          go tool cover -func=v1beta2-coverage.out | grep -vE "(total:|\.pb\.go:)" >> "$GITHUB_STEP_SUMMARY"

          echo "</details>" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          echo "### Total Coverage:" >> "$GITHUB_STEP_SUMMARY"
          go tool cover -func=v1beta2-coverage.out | grep total | awk '{print "**"$3"**"}' | tee -a "$GITHUB_STEP_SUMMARY"
        shell: bash


