name: Verify Schema Tarball

on:
  pull_request:
    branches: ['main']
    paths:
      - 'data/schema/**'
      - 'resources.tar.gz'

permissions:
  contents: read
  pull-requests: write

jobs:
  verify-tarball-updated:
    name: Verify schema tarball is updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for accurate diff

      - name: Get changed files
        id: changed-files
        run: |
          # Get the list of changed files in the PR
          git fetch origin ${{ github.base_ref }}
          
          # Check if schema files changed
          SCHEMA_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -c '^data/schema/' || true)
          echo "schema_changed=${SCHEMA_CHANGED}" >> $GITHUB_OUTPUT
          
          # Check if tarball changed
          TARBALL_CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -c '^resources\.tar\.gz$' || true)
          echo "tarball_changed=${TARBALL_CHANGED}" >> $GITHUB_OUTPUT
          
          echo "Schema files changed: ${SCHEMA_CHANGED}"
          echo "Tarball changed: ${TARBALL_CHANGED}"

      - name: Verify tarball updated when schema changes
        id: verify
        run: |
          SCHEMA_CHANGED=${{ steps.changed-files.outputs.schema_changed }}
          TARBALL_CHANGED=${{ steps.changed-files.outputs.tarball_changed }}
          
          if [ "${SCHEMA_CHANGED}" -gt 0 ] && [ "${TARBALL_CHANGED}" -eq 0 ]; then
            echo "::error::Schema files in data/schema/ were modified but resources.tar.gz was not updated!"
            echo "::error::Please run 'make build-schemas' to regenerate the tarball."
            echo "status=failed" >> $GITHUB_OUTPUT
            exit 1
          elif [ "${SCHEMA_CHANGED}" -eq 0 ] && [ "${TARBALL_CHANGED}" -gt 0 ]; then
            echo "::warning::resources.tar.gz was modified but no schema files changed. This may be intentional, but please verify."
            echo "status=warning" >> $GITHUB_OUTPUT
          else
            echo "✅ Schema and tarball changes are in sync."
            echo "status=success" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## ⚠️ Schema Tarball Not Updated\n\n' +
                    'Changes were detected in `data/schema/` but the `resources.tar.gz` file was not updated.\n\n' +
                    '### How to fix:\n' +
                    '1. Run `make build-schemas` to regenerate the tarball\n' +
                    '2. Commit the updated `resources.tar.gz` and `deploy/kessel-inventory-ephem.yaml` files\n' +
                    '3. Push the changes to your PR\n\n' +
                    '### Why this is required:\n' +
                    'The tarball must be rebuilt whenever schema configs change to ensure the changes are captured and consumable in deployments.'
            })
